import { ChangeDetectionStrategy, Component, computed, signal } from '@angular/core';
import type { WritableSignal, Signal } from '@angular/core';
import { CommonModule } from '@angular/common';
import { RouterModule } from '@angular/router';
import { DocPageLayoutComponent } from '@demo/shared/doc-page/doc-page-layout.component';
import type { DocSection } from '@demo/shared/doc-page/doc-section.model';

export interface ComponentScore {
  name: string;
  category: string;
  api: number;
  a11y: number;
  perf: number;
  comp: number;
  theme: number;
  dx: number;
  docs: number;
  polish: number;
  angular: number;
  feel: number;
  avg: number;
}

export interface PhaseInfo {
  id: number;
  name: string;
  description: string;
  status: 'complete' | 'active' | 'queued';
  componentCount: number | null;
  completedCount: number | null;
  exitCriteria: string[];
  milestone?: string;
}

export interface NextStep {
  title: string;
  description: string;
  priority: 'critical' | 'high' | 'medium';
  category: string;
}

export interface WowFactor {
  number: number;
  title: string;
  tagline: string;
  status: 'achieved' | 'in-progress' | 'queued';
  items: string[];
}

/**
 * Roadmap and progress tracker page for the ui-lib-custom library.
 * Displays dashboard stats, milestone phases, component quality scores, next steps, and wow factors.
 */
@Component({
  selector: 'app-roadmap',
  standalone: true,
  imports: [CommonModule, RouterModule, DocPageLayoutComponent],
  templateUrl: './roadmap.component.html',
  styleUrl: './roadmap.component.scss',
  changeDetection: ChangeDetectionStrategy.OnPush,
})
export class RoadmapComponent {
  public readonly sections: DocSection[] = [
    { id: 'dashboard', label: 'Dashboard' },
    { id: 'milestone-progress', label: 'Milestone Progress' },
    { id: 'component-scoreboard', label: 'Component Scoreboard' },
    { id: 'next-steps', label: 'Next Steps' },
    { id: 'wow-factors', label: 'Wow Factors' },
  ];

  // ── Filter state ─────────────────────────────────────────────────────────
  public readonly searchQuery: WritableSignal<string> = signal<string>('');
  public readonly activeCategory: WritableSignal<string> = signal<string>('All');

  public readonly categories: string[] = [
    'All',
    'Core Inputs',
    'Layout',
    'Overlay & Modal',
    'Navigation & Menus',
    'Data Display',
    'Feedback & Status',
    'Utilities & Directives',
  ];

  // ── Component score data ──────────────────────────────────────────────────
  public readonly allComponents: ComponentScore[] = [
    // Core Inputs
    {
      name: 'Button',
      category: 'Core Inputs',
      api: 9,
      a11y: 9,
      perf: 9,
      comp: 8,
      theme: 9,
      dx: 9,
      docs: 9,
      polish: 9,
      angular: 9,
      feel: 9,
      avg: 8.9,
    },
    {
      name: 'Input',
      category: 'Core Inputs',
      api: 9,
      a11y: 9,
      perf: 9,
      comp: 8,
      theme: 8,
      dx: 9,
      docs: 9,
      polish: 9,
      angular: 9,
      feel: 9,
      avg: 8.8,
    },
    {
      name: 'Textarea',
      category: 'Core Inputs',
      api: 9,
      a11y: 9,
      perf: 9,
      comp: 8,
      theme: 9,
      dx: 9,
      docs: 9,
      polish: 8,
      angular: 9,
      feel: 8,
      avg: 8.7,
    },
    {
      name: 'Select',
      category: 'Core Inputs',
      api: 8,
      a11y: 9,
      perf: 8,
      comp: 8,
      theme: 8,
      dx: 8,
      docs: 8,
      polish: 8,
      angular: 9,
      feel: 8,
      avg: 8.2,
    },
    {
      name: 'AutoComplete',
      category: 'Core Inputs',
      api: 8,
      a11y: 9,
      perf: 8,
      comp: 8,
      theme: 8,
      dx: 8,
      docs: 8,
      polish: 8,
      angular: 9,
      feel: 8,
      avg: 8.2,
    },
    {
      name: 'CascadeSelect',
      category: 'Core Inputs',
      api: 8,
      a11y: 9,
      perf: 8,
      comp: 8,
      theme: 8,
      dx: 8,
      docs: 8,
      polish: 8,
      angular: 9,
      feel: 8,
      avg: 8.2,
    },
    {
      name: 'Checkbox',
      category: 'Core Inputs',
      api: 9,
      a11y: 9,
      perf: 9,
      comp: 9,
      theme: 9,
      dx: 9,
      docs: 9,
      polish: 9,
      angular: 9,
      feel: 9,
      avg: 9.0,
    },
    {
      name: 'RadioButton',
      category: 'Core Inputs',
      api: 9,
      a11y: 9,
      perf: 9,
      comp: 8,
      theme: 9,
      dx: 9,
      docs: 9,
      polish: 9,
      angular: 9,
      feel: 8,
      avg: 8.8,
    },
    {
      name: 'ToggleButton',
      category: 'Core Inputs',
      api: 9,
      a11y: 9,
      perf: 9,
      comp: 8,
      theme: 9,
      dx: 9,
      docs: 9,
      polish: 8,
      angular: 9,
      feel: 8,
      avg: 8.7,
    },
    {
      name: 'ToggleSwitch',
      category: 'Core Inputs',
      api: 9,
      a11y: 9,
      perf: 9,
      comp: 8,
      theme: 9,
      dx: 9,
      docs: 9,
      polish: 9,
      angular: 9,
      feel: 8,
      avg: 8.8,
    },
    {
      name: 'SelectButton',
      category: 'Core Inputs',
      api: 9,
      a11y: 9,
      perf: 9,
      comp: 8,
      theme: 9,
      dx: 9,
      docs: 9,
      polish: 8,
      angular: 9,
      feel: 8,
      avg: 8.7,
    },
    {
      name: 'InputNumber',
      category: 'Core Inputs',
      api: 9,
      a11y: 9,
      perf: 9,
      comp: 9,
      theme: 9,
      dx: 9,
      docs: 9,
      polish: 9,
      angular: 9,
      feel: 9,
      avg: 9.0,
    },
    {
      name: 'InputMask',
      category: 'Core Inputs',
      api: 9,
      a11y: 9,
      perf: 9,
      comp: 8,
      theme: 9,
      dx: 9,
      docs: 9,
      polish: 8,
      angular: 9,
      feel: 8,
      avg: 8.7,
    },
    {
      name: 'InputOtp',
      category: 'Core Inputs',
      api: 9,
      a11y: 9,
      perf: 9,
      comp: 8,
      theme: 9,
      dx: 9,
      docs: 9,
      polish: 8,
      angular: 9,
      feel: 8,
      avg: 8.7,
    },
    {
      name: 'Password',
      category: 'Core Inputs',
      api: 9,
      a11y: 9,
      perf: 9,
      comp: 8,
      theme: 9,
      dx: 9,
      docs: 9,
      polish: 8,
      angular: 9,
      feel: 8,
      avg: 8.7,
    },
    {
      name: 'Rating',
      category: 'Core Inputs',
      api: 9,
      a11y: 9,
      perf: 9,
      comp: 8,
      theme: 9,
      dx: 9,
      docs: 9,
      polish: 8,
      angular: 9,
      feel: 8,
      avg: 8.7,
    },
    {
      name: 'Knob',
      category: 'Core Inputs',
      api: 8,
      a11y: 9,
      perf: 8,
      comp: 8,
      theme: 8,
      dx: 8,
      docs: 8,
      polish: 8,
      angular: 9,
      feel: 8,
      avg: 8.2,
    },
    {
      name: 'Slider',
      category: 'Core Inputs',
      api: 9,
      a11y: 9,
      perf: 9,
      comp: 9,
      theme: 9,
      dx: 9,
      docs: 9,
      polish: 8,
      angular: 9,
      feel: 8,
      avg: 8.8,
    },
    {
      name: 'ColorPicker',
      category: 'Core Inputs',
      api: 8,
      a11y: 9,
      perf: 8,
      comp: 8,
      theme: 8,
      dx: 8,
      docs: 8,
      polish: 8,
      angular: 9,
      feel: 8,
      avg: 8.2,
    },
    {
      name: 'KeyFilter',
      category: 'Core Inputs',
      api: 9,
      a11y: 9,
      perf: 9,
      comp: 8,
      theme: 8,
      dx: 9,
      docs: 9,
      polish: 8,
      angular: 9,
      feel: 8,
      avg: 8.6,
    },
    // Layout
    {
      name: 'Card',
      category: 'Layout',
      api: 9,
      a11y: 9,
      perf: 9,
      comp: 9,
      theme: 9,
      dx: 9,
      docs: 9,
      polish: 9,
      angular: 9,
      feel: 9,
      avg: 9.0,
    },
    {
      name: 'Stack',
      category: 'Layout',
      api: 9,
      a11y: 9,
      perf: 9,
      comp: 9,
      theme: 9,
      dx: 9,
      docs: 9,
      polish: 9,
      angular: 9,
      feel: 9,
      avg: 9.0,
    },
    {
      name: 'Inline',
      category: 'Layout',
      api: 9,
      a11y: 9,
      perf: 9,
      comp: 9,
      theme: 9,
      dx: 9,
      docs: 9,
      polish: 9,
      angular: 9,
      feel: 9,
      avg: 9.0,
    },
    {
      name: 'Grid',
      category: 'Layout',
      api: 9,
      a11y: 9,
      perf: 9,
      comp: 9,
      theme: 9,
      dx: 9,
      docs: 9,
      polish: 9,
      angular: 9,
      feel: 9,
      avg: 9.0,
    },
    {
      name: 'Container',
      category: 'Layout',
      api: 9,
      a11y: 9,
      perf: 9,
      comp: 9,
      theme: 8,
      dx: 9,
      docs: 9,
      polish: 9,
      angular: 9,
      feel: 9,
      avg: 8.9,
    },
    {
      name: 'FloatLabel',
      category: 'Layout',
      api: 9,
      a11y: 9,
      perf: 10,
      comp: 8,
      theme: 8,
      dx: 9,
      docs: 9,
      polish: 8,
      angular: 9,
      feel: 8,
      avg: 8.7,
    },
    {
      name: 'IconField',
      category: 'Layout',
      api: 9,
      a11y: 9,
      perf: 9,
      comp: 8,
      theme: 9,
      dx: 9,
      docs: 9,
      polish: 8,
      angular: 9,
      feel: 8,
      avg: 8.7,
    },
    {
      name: 'InputGroup',
      category: 'Layout',
      api: 9,
      a11y: 9,
      perf: 9,
      comp: 8,
      theme: 9,
      dx: 9,
      docs: 9,
      polish: 8,
      angular: 9,
      feel: 8,
      avg: 8.7,
    },
    {
      name: 'FormField',
      category: 'Layout',
      api: 9,
      a11y: 9,
      perf: 9,
      comp: 8,
      theme: 8,
      dx: 9,
      docs: 9,
      polish: 8,
      angular: 9,
      feel: 9,
      avg: 8.7,
    },
    {
      name: 'Divider',
      category: 'Layout',
      api: 9,
      a11y: 9,
      perf: 9,
      comp: 8,
      theme: 9,
      dx: 9,
      docs: 9,
      polish: 8,
      angular: 9,
      feel: 8,
      avg: 8.7,
    },
    {
      name: 'Toolbar',
      category: 'Layout',
      api: 9,
      a11y: 9,
      perf: 9,
      comp: 8,
      theme: 9,
      dx: 9,
      docs: 9,
      polish: 9,
      angular: 9,
      feel: 9,
      avg: 8.9,
    },
    {
      name: 'Fluid',
      category: 'Layout',
      api: 9,
      a11y: 9,
      perf: 9,
      comp: 9,
      theme: 8,
      dx: 9,
      docs: 8,
      polish: 9,
      angular: 9,
      feel: 8,
      avg: 8.7,
    },
    {
      name: 'Fieldset',
      category: 'Layout',
      api: 9,
      a11y: 9,
      perf: 9,
      comp: 9,
      theme: 9,
      dx: 9,
      docs: 9,
      polish: 9,
      angular: 9,
      feel: 9,
      avg: 9.0,
    },
    {
      name: 'Panel',
      category: 'Layout',
      api: 9,
      a11y: 9,
      perf: 9,
      comp: 9,
      theme: 9,
      dx: 9,
      docs: 9,
      polish: 9,
      angular: 9,
      feel: 9,
      avg: 9.0,
    },
    {
      name: 'ScrollPanel',
      category: 'Layout',
      api: 9,
      a11y: 9,
      perf: 9,
      comp: 8,
      theme: 9,
      dx: 9,
      docs: 9,
      polish: 9,
      angular: 9,
      feel: 9,
      avg: 8.9,
    },
    // Overlay & Modal
    {
      name: 'Dialog',
      category: 'Overlay & Modal',
      api: 9,
      a11y: 9,
      perf: 8,
      comp: 9,
      theme: 8,
      dx: 9,
      docs: 8,
      polish: 9,
      angular: 9,
      feel: 8,
      avg: 8.6,
    },
    {
      name: 'DynamicDialog',
      category: 'Overlay & Modal',
      api: 9,
      a11y: 9,
      perf: 8,
      comp: 8,
      theme: 8,
      dx: 8,
      docs: 8,
      polish: 8,
      angular: 9,
      feel: 8,
      avg: 8.3,
    },
    {
      name: 'Drawer',
      category: 'Overlay & Modal',
      api: 9,
      a11y: 9,
      perf: 8,
      comp: 8,
      theme: 9,
      dx: 8,
      docs: 9,
      polish: 8,
      angular: 9,
      feel: 8,
      avg: 8.5,
    },
    {
      name: 'BottomSheet',
      category: 'Overlay & Modal',
      api: 8,
      a11y: 9,
      perf: 8,
      comp: 8,
      theme: 9,
      dx: 9,
      docs: 9,
      polish: 8,
      angular: 9,
      feel: 8,
      avg: 8.5,
    },
    {
      name: 'Popover',
      category: 'Overlay & Modal',
      api: 9,
      a11y: 9,
      perf: 9,
      comp: 9,
      theme: 9,
      dx: 9,
      docs: 9,
      polish: 9,
      angular: 9,
      feel: 9,
      avg: 9.0,
    },
    {
      name: 'Tooltip',
      category: 'Overlay & Modal',
      api: 9,
      a11y: 9,
      perf: 9,
      comp: 9,
      theme: 9,
      dx: 9,
      docs: 9,
      polish: 9,
      angular: 9,
      feel: 9,
      avg: 9.0,
    },
    {
      name: 'ConfirmDialog',
      category: 'Overlay & Modal',
      api: 9,
      a11y: 9,
      perf: 8,
      comp: 8,
      theme: 8,
      dx: 8,
      docs: 8,
      polish: 8,
      angular: 9,
      feel: 8,
      avg: 8.3,
    },
    {
      name: 'ConfirmPopup',
      category: 'Overlay & Modal',
      api: 9,
      a11y: 9,
      perf: 9,
      comp: 9,
      theme: 9,
      dx: 8,
      docs: 9,
      polish: 9,
      angular: 9,
      feel: 9,
      avg: 8.9,
    },
    // Navigation & Menus
    {
      name: 'Tabs',
      category: 'Navigation & Menus',
      api: 9,
      a11y: 9,
      perf: 9,
      comp: 9,
      theme: 9,
      dx: 9,
      docs: 9,
      polish: 9,
      angular: 9,
      feel: 9,
      avg: 9.0,
    },
    {
      name: 'Accordion',
      category: 'Navigation & Menus',
      api: 9,
      a11y: 9,
      perf: 9,
      comp: 9,
      theme: 9,
      dx: 9,
      docs: 9,
      polish: 9,
      angular: 9,
      feel: 9,
      avg: 9.0,
    },
    {
      name: 'Breadcrumb',
      category: 'Navigation & Menus',
      api: 9,
      a11y: 9,
      perf: 9,
      comp: 9,
      theme: 9,
      dx: 9,
      docs: 9,
      polish: 9,
      angular: 9,
      feel: 9,
      avg: 9.0,
    },
    {
      name: 'ContextMenu',
      category: 'Navigation & Menus',
      api: 9,
      a11y: 9,
      perf: 9,
      comp: 9,
      theme: 9,
      dx: 9,
      docs: 9,
      polish: 9,
      angular: 9,
      feel: 9,
      avg: 9.0,
    },
    {
      name: 'Dock',
      category: 'Navigation & Menus',
      api: 9,
      a11y: 9,
      perf: 9,
      comp: 9,
      theme: 9,
      dx: 9,
      docs: 9,
      polish: 9,
      angular: 9,
      feel: 9,
      avg: 9.0,
    },
    {
      name: 'Menu',
      category: 'Navigation & Menus',
      api: 9,
      a11y: 9,
      perf: 9,
      comp: 9,
      theme: 9,
      dx: 9,
      docs: 9,
      polish: 9,
      angular: 9,
      feel: 9,
      avg: 9.0,
    },
    {
      name: 'MegaMenu',
      category: 'Navigation & Menus',
      api: 9,
      a11y: 9,
      perf: 9,
      comp: 9,
      theme: 9,
      dx: 9,
      docs: 9,
      polish: 9,
      angular: 9,
      feel: 9,
      avg: 9.0,
    },
    {
      name: 'Menubar',
      category: 'Navigation & Menus',
      api: 9,
      a11y: 9,
      perf: 9,
      comp: 9,
      theme: 9,
      dx: 9,
      docs: 9,
      polish: 9,
      angular: 9,
      feel: 9,
      avg: 9.0,
    },
    {
      name: 'PanelMenu',
      category: 'Navigation & Menus',
      api: 9,
      a11y: 9,
      perf: 9,
      comp: 9,
      theme: 9,
      dx: 9,
      docs: 9,
      polish: 9,
      angular: 9,
      feel: 9,
      avg: 9.0,
    },
    {
      name: 'TieredMenu',
      category: 'Navigation & Menus',
      api: 9,
      a11y: 9,
      perf: 9,
      comp: 9,
      theme: 9,
      dx: 9,
      docs: 9,
      polish: 9,
      angular: 9,
      feel: 9,
      avg: 9.0,
    },
    {
      name: 'Stepper',
      category: 'Navigation & Menus',
      api: 9,
      a11y: 9,
      perf: 9,
      comp: 9,
      theme: 9,
      dx: 9,
      docs: 9,
      polish: 9,
      angular: 9,
      feel: 9,
      avg: 9.0,
    },
    {
      name: 'SpeedDial',
      category: 'Navigation & Menus',
      api: 9,
      a11y: 9,
      perf: 9,
      comp: 9,
      theme: 9,
      dx: 9,
      docs: 9,
      polish: 8,
      angular: 9,
      feel: 8,
      avg: 8.8,
    },
    // Data Display
    {
      name: 'Table',
      category: 'Data Display',
      api: 9,
      a11y: 9,
      perf: 8,
      comp: 8,
      theme: 9,
      dx: 9,
      docs: 9,
      polish: 8,
      angular: 9,
      feel: 8,
      avg: 8.6,
    },
    {
      name: 'TreeTable',
      category: 'Data Display',
      api: 9,
      a11y: 9,
      perf: 8,
      comp: 8,
      theme: 8,
      dx: 9,
      docs: 9,
      polish: 8,
      angular: 9,
      feel: 8,
      avg: 8.5,
    },
    {
      name: 'Tree',
      category: 'Data Display',
      api: 9,
      a11y: 8,
      perf: 9,
      comp: 9,
      theme: 9,
      dx: 9,
      docs: 8,
      polish: 8,
      angular: 9,
      feel: 8,
      avg: 8.6,
    },
    {
      name: 'TreeSelect',
      category: 'Data Display',
      api: 9,
      a11y: 9,
      perf: 8,
      comp: 8,
      theme: 9,
      dx: 9,
      docs: 9,
      polish: 8,
      angular: 9,
      feel: 8,
      avg: 8.6,
    },
    {
      name: 'Listbox',
      category: 'Data Display',
      api: 9,
      a11y: 9,
      perf: 8,
      comp: 8,
      theme: 9,
      dx: 9,
      docs: 9,
      polish: 8,
      angular: 9,
      feel: 8,
      avg: 8.6,
    },
    {
      name: 'DataView',
      category: 'Data Display',
      api: 8,
      a11y: 9,
      perf: 8,
      comp: 8,
      theme: 8,
      dx: 8,
      docs: 9,
      polish: 8,
      angular: 9,
      feel: 8,
      avg: 8.3,
    },
    {
      name: 'VirtualScroller',
      category: 'Data Display',
      api: 8,
      a11y: 9,
      perf: 9,
      comp: 8,
      theme: 8,
      dx: 9,
      docs: 9,
      polish: 8,
      angular: 9,
      feel: 8,
      avg: 8.5,
    },
    {
      name: 'Timeline',
      category: 'Data Display',
      api: 8,
      a11y: 9,
      perf: 8,
      comp: 8,
      theme: 8,
      dx: 8,
      docs: 9,
      polish: 8,
      angular: 9,
      feel: 8,
      avg: 8.3,
    },
    {
      name: 'OrderList',
      category: 'Data Display',
      api: 9,
      a11y: 9,
      perf: 9,
      comp: 8,
      theme: 9,
      dx: 9,
      docs: 9,
      polish: 8,
      angular: 9,
      feel: 8,
      avg: 8.7,
    },
    {
      name: 'OrganizationChart',
      category: 'Data Display',
      api: 8,
      a11y: 9,
      perf: 8,
      comp: 8,
      theme: 8,
      dx: 8,
      docs: 9,
      polish: 8,
      angular: 9,
      feel: 8,
      avg: 8.3,
    },
    {
      name: 'PickList',
      category: 'Data Display',
      api: 9,
      a11y: 9,
      perf: 9,
      comp: 8,
      theme: 9,
      dx: 9,
      docs: 9,
      polish: 8,
      angular: 9,
      feel: 8,
      avg: 8.7,
    },
    {
      name: 'Paginator',
      category: 'Data Display',
      api: 8,
      a11y: 9,
      perf: 9,
      comp: 8,
      theme: 8,
      dx: 9,
      docs: 9,
      polish: 8,
      angular: 9,
      feel: 8,
      avg: 8.5,
    },
    {
      name: 'Carousel',
      category: 'Data Display',
      api: 8,
      a11y: 9,
      perf: 8,
      comp: 8,
      theme: 8,
      dx: 8,
      docs: 9,
      polish: 8,
      angular: 9,
      feel: 8,
      avg: 8.3,
    },
    {
      name: 'Galleria',
      category: 'Data Display',
      api: 8,
      a11y: 9,
      perf: 8,
      comp: 8,
      theme: 8,
      dx: 8,
      docs: 9,
      polish: 8,
      angular: 9,
      feel: 8,
      avg: 8.3,
    },
    {
      name: 'Chart',
      category: 'Data Display',
      api: 9,
      a11y: 9,
      perf: 9,
      comp: 8,
      theme: 9,
      dx: 9,
      docs: 9,
      polish: 9,
      angular: 9,
      feel: 9,
      avg: 8.9,
    },
    // Feedback & Status
    {
      name: 'Alert',
      category: 'Feedback & Status',
      api: 9,
      a11y: 9,
      perf: 8,
      comp: 8,
      theme: 8,
      dx: 9,
      docs: 9,
      polish: 8,
      angular: 9,
      feel: 8,
      avg: 8.5,
    },
    {
      name: 'Toast',
      category: 'Feedback & Status',
      api: 9,
      a11y: 10,
      perf: 9,
      comp: 9,
      theme: 9,
      dx: 9,
      docs: 9,
      polish: 9,
      angular: 9,
      feel: 9,
      avg: 9.1,
    },
    {
      name: 'Badge',
      category: 'Feedback & Status',
      api: 8,
      a11y: 9,
      perf: 9,
      comp: 8,
      theme: 8,
      dx: 8,
      docs: 9,
      polish: 8,
      angular: 9,
      feel: 8,
      avg: 8.4,
    },
    {
      name: 'Tag',
      category: 'Feedback & Status',
      api: 9,
      a11y: 9,
      perf: 9,
      comp: 8,
      theme: 9,
      dx: 9,
      docs: 9,
      polish: 9,
      angular: 9,
      feel: 9,
      avg: 8.9,
    },
    {
      name: 'Chip',
      category: 'Feedback & Status',
      api: 9,
      a11y: 9,
      perf: 8,
      comp: 8,
      theme: 8,
      dx: 9,
      docs: 9,
      polish: 8,
      angular: 9,
      feel: 8,
      avg: 8.5,
    },
    {
      name: 'Message',
      category: 'Feedback & Status',
      api: 9,
      a11y: 9,
      perf: 8,
      comp: 8,
      theme: 9,
      dx: 9,
      docs: 9,
      polish: 8,
      angular: 9,
      feel: 8,
      avg: 8.6,
    },
    {
      name: 'Skeleton',
      category: 'Feedback & Status',
      api: 9,
      a11y: 9,
      perf: 9,
      comp: 8,
      theme: 9,
      dx: 8,
      docs: 9,
      polish: 8,
      angular: 9,
      feel: 8,
      avg: 8.6,
    },
    {
      name: 'ProgressBar',
      category: 'Feedback & Status',
      api: 9,
      a11y: 9,
      perf: 9,
      comp: 8,
      theme: 9,
      dx: 9,
      docs: 9,
      polish: 8,
      angular: 9,
      feel: 8,
      avg: 8.6,
    },
    {
      name: 'ProgressSpinner',
      category: 'Feedback & Status',
      api: 9,
      a11y: 9,
      perf: 9,
      comp: 8,
      theme: 9,
      dx: 9,
      docs: 9,
      polish: 9,
      angular: 9,
      feel: 9,
      avg: 8.9,
    },
    {
      name: 'MeterGroup',
      category: 'Feedback & Status',
      api: 8,
      a11y: 9,
      perf: 8,
      comp: 8,
      theme: 8,
      dx: 8,
      docs: 9,
      polish: 8,
      angular: 9,
      feel: 8,
      avg: 8.3,
    },
    // Utilities & Directives
    {
      name: 'Avatar',
      category: 'Utilities & Directives',
      api: 8,
      a11y: 9,
      perf: 8,
      comp: 8,
      theme: 8,
      dx: 8,
      docs: 8,
      polish: 8,
      angular: 9,
      feel: 8,
      avg: 8.2,
    },
    {
      name: 'Icon',
      category: 'Utilities & Directives',
      api: 9,
      a11y: 9,
      perf: 9,
      comp: 8,
      theme: 9,
      dx: 9,
      docs: 9,
      polish: 8,
      angular: 9,
      feel: 8,
      avg: 8.7,
    },
    {
      name: 'IconButton',
      category: 'Utilities & Directives',
      api: 9,
      a11y: 9,
      perf: 9,
      comp: 8,
      theme: 8,
      dx: 9,
      docs: 9,
      polish: 8,
      angular: 9,
      feel: 8,
      avg: 8.6,
    },
    {
      name: 'ButtonGroup',
      category: 'Utilities & Directives',
      api: 9,
      a11y: 9,
      perf: 9,
      comp: 8,
      theme: 9,
      dx: 9,
      docs: 9,
      polish: 8,
      angular: 9,
      feel: 8,
      avg: 8.7,
    },
    {
      name: 'SplitButton',
      category: 'Utilities & Directives',
      api: 9,
      a11y: 9,
      perf: 8,
      comp: 8,
      theme: 9,
      dx: 9,
      docs: 9,
      polish: 8,
      angular: 9,
      feel: 8,
      avg: 8.6,
    },
    {
      name: 'Image',
      category: 'Utilities & Directives',
      api: 9,
      a11y: 9,
      perf: 9,
      comp: 8,
      theme: 9,
      dx: 9,
      docs: 9,
      polish: 8,
      angular: 9,
      feel: 8,
      avg: 8.7,
    },
    {
      name: 'ImageCompare',
      category: 'Utilities & Directives',
      api: 9,
      a11y: 9,
      perf: 9,
      comp: 8,
      theme: 9,
      dx: 9,
      docs: 9,
      polish: 9,
      angular: 9,
      feel: 9,
      avg: 8.9,
    },
    {
      name: 'Upload',
      category: 'Utilities & Directives',
      api: 9,
      a11y: 9,
      perf: 9,
      comp: 8,
      theme: 9,
      dx: 9,
      docs: 9,
      polish: 9,
      angular: 9,
      feel: 9,
      avg: 8.9,
    },
    {
      name: 'Inplace',
      category: 'Utilities & Directives',
      api: 9,
      a11y: 9,
      perf: 9,
      comp: 8,
      theme: 9,
      dx: 9,
      docs: 9,
      polish: 9,
      angular: 9,
      feel: 9,
      avg: 8.9,
    },
    {
      name: 'BlockUI',
      category: 'Utilities & Directives',
      api: 9,
      a11y: 9,
      perf: 9,
      comp: 9,
      theme: 9,
      dx: 9,
      docs: 9,
      polish: 9,
      angular: 9,
      feel: 9,
      avg: 9.0,
    },
    {
      name: 'ClassNames',
      category: 'Utilities & Directives',
      api: 9,
      a11y: 9,
      perf: 10,
      comp: 9,
      theme: 9,
      dx: 9,
      docs: 9,
      polish: 9,
      angular: 9,
      feel: 9,
      avg: 9.1,
    },
    {
      name: 'Terminal',
      category: 'Utilities & Directives',
      api: 9,
      a11y: 9,
      perf: 9,
      comp: 8,
      theme: 9,
      dx: 9,
      docs: 9,
      polish: 9,
      angular: 9,
      feel: 9,
      avg: 8.9,
    },
    {
      name: 'Ripple',
      category: 'Utilities & Directives',
      api: 8,
      a11y: 9,
      perf: 9,
      comp: 8,
      theme: 8,
      dx: 9,
      docs: 9,
      polish: 9,
      angular: 9,
      feel: 9,
      avg: 8.7,
    },
    {
      name: 'ScrollTop',
      category: 'Utilities & Directives',
      api: 8,
      a11y: 9,
      perf: 8,
      comp: 8,
      theme: 9,
      dx: 8,
      docs: 9,
      polish: 8,
      angular: 9,
      feel: 8,
      avg: 8.4,
    },
    {
      name: 'StyleClass',
      category: 'Utilities & Directives',
      api: 9,
      a11y: 9,
      perf: 9,
      comp: 9,
      theme: 8,
      dx: 9,
      docs: 9,
      polish: 8,
      angular: 9,
      feel: 8,
      avg: 8.7,
    },
    {
      name: 'FocusTrap',
      category: 'Utilities & Directives',
      api: 8,
      a11y: 9,
      perf: 9,
      comp: 8,
      theme: 8,
      dx: 8,
      docs: 9,
      polish: 8,
      angular: 9,
      feel: 8,
      avg: 8.4,
    },
    {
      name: 'AnimateOnScroll',
      category: 'Utilities & Directives',
      api: 9,
      a11y: 9,
      perf: 9,
      comp: 8,
      theme: 8,
      dx: 9,
      docs: 9,
      polish: 8,
      angular: 9,
      feel: 8,
      avg: 8.6,
    },
    {
      name: 'AutoFocus',
      category: 'Utilities & Directives',
      api: 9,
      a11y: 9,
      perf: 10,
      comp: 8,
      theme: 8,
      dx: 9,
      docs: 9,
      polish: 8,
      angular: 9,
      feel: 8,
      avg: 8.7,
    },
    {
      name: 'Bind',
      category: 'Utilities & Directives',
      api: 8,
      a11y: 9,
      perf: 9,
      comp: 9,
      theme: 8,
      dx: 9,
      docs: 9,
      polish: 8,
      angular: 9,
      feel: 8,
      avg: 8.6,
    },
  ];

  // ── Filtered components ───────────────────────────────────────────────────
  public readonly filteredComponents: Signal<ComponentScore[]> = computed<ComponentScore[]>(
    (): ComponentScore[] => {
      const query: string = this.searchQuery().toLowerCase().trim();
      const cat: string = this.activeCategory();
      return this.allComponents.filter((component: ComponentScore): boolean => {
        const matchesCategory: boolean = cat === 'All' || component.category === cat;
        const matchesQuery: boolean = query === '' || component.name.toLowerCase().includes(query);
        return matchesCategory && matchesQuery;
      });
    }
  );

  // ── Dashboard stats ───────────────────────────────────────────────────────
  public readonly totalComponents: Signal<number> = computed<number>(
    (): number => this.allComponents.length
  );

  public readonly averageScore: Signal<string> = computed<string>((): string => {
    const total: number = this.allComponents.reduce(
      (sum: number, c: ComponentScore): number => sum + c.avg,
      0
    );
    return (total / this.allComponents.length).toFixed(2);
  });

  public readonly perfectScoreCount: Signal<number> = computed<number>(
    (): number => this.allComponents.filter((c: ComponentScore): boolean => c.avg >= 9.0).length
  );

  public readonly categoryBreakdown: Signal<{ name: string; count: number }[]> = computed<
    { name: string; count: number }[]
  >((): { name: string; count: number }[] => {
    const map: Map<string, number> = new Map<string, number>();
    this.allComponents.forEach((component: ComponentScore): void => {
      map.set(component.category, (map.get(component.category) ?? 0) + 1);
    });
    return Array.from(map.entries()).map(
      ([name, count]: [string, number]): { name: string; count: number } => ({ name, count })
    );
  });

  // ── Phases ────────────────────────────────────────────────────────────────
  public readonly phases: PhaseInfo[] = [
    {
      id: 0,
      name: 'Foundation Cleanup',
      description:
        'Infrastructure gaps closed, entry points wired, dead-code baseline established.',
      status: 'complete',
      componentCount: null,
      completedCount: null,
      exitCriteria: [
        'Secondary entry points for all components created',
        'Overlay appendTo / z-index manager in place',
        'knip dead-code baseline complete',
        'Documentation gaps resolved for core components',
      ],
    },
    {
      id: 1,
      name: 'Elite A11y — Overlays & Navigation',
      description:
        'The most complex ARIA patterns correct, tested, and audited. Focus traps, aria-modal, menu keyboard navigation.',
      status: 'complete',
      componentCount: 17,
      completedCount: 17,
      exitCriteria: [
        'All 17 overlay & navigation components scored ≥ 8',
        'Internal axe-core audit run — violations resolved',
        'Zero open a11y regressions in Tier 1 or Tier 2',
      ],
    },
    {
      id: 2,
      name: 'Elite A11y — Forms & Data Display',
      description:
        'Form controls and data components production-quality. Daily-driver components developers trust.',
      status: 'complete',
      componentCount: 20,
      completedCount: 20,
      exitCriteria: [
        'All 20 form & data components scored ≥ 8',
        'DatePicker and Table pass screen reader spot-check',
        'No open regressions across Tiers 1–4',
      ],
    },
    {
      id: 3,
      name: 'Full Coverage + Ecosystem',
      description: 'Every component green. Library ready to be shown publicly.',
      status: 'complete',
      componentCount: 76,
      completedCount: 76,
      exitCriteria: [
        'All 76 original components scored ≥ 8',
        'All new components (24+) scored ≥ 8',
        'Storybook integration deployed',
        'Full axe-core audit — zero violations target',
        'npm run test:a11y:all passes',
      ],
      milestone: 'Component Hardening Milestone ACHIEVED ✅',
    },
    {
      id: 4,
      name: 'Public Beta 🚀',
      description: 'First public release. Library is on npm. Developers can use it.',
      status: 'active',
      componentCount: null,
      completedCount: null,
      exitCriteria: [
        'npm publish — first public version (0.9.0)',
        'Landing page live with benchmark claims',
        'Documentation site live with interactive demos',
        'Open benchmark repo published (axe-core, Angular modernity, bundle sizes)',
        'Competitive positioning content ready',
        'Community announcement — Angular channels, Dev.to, X/Twitter',
      ],
      milestone: 'NEXT MAJOR MILESTONE',
    },
    {
      id: 5,
      name: 'v1.0 General Availability 🏆',
      description: 'Wow Factor #2 complete. The library is what it set out to be.',
      status: 'queued',
      componentCount: null,
      completedCount: null,
      exitCriteria: [
        'Runtime theme switching — seamless, no flash',
        'Full --uilib-* CSS var coverage across all components',
        'Theme preset management (multiple built-in presets)',
        'Brand customization path — documented, < 30 min to custom brand',
        'Every component at scorecard ≥ 9 average',
        'Zero open a11y issues from community reports',
        'Storybook stories cover all variants',
        'Version tagged 1.0.0 on npm',
      ],
      milestone: 'WOW FACTOR #2 TARGET',
    },
  ];

  // ── Next Steps ────────────────────────────────────────────────────────────
  public readonly nextSteps: NextStep[] = [
    {
      title: 'Runtime Variant Switcher',
      description:
        'Implement seamless runtime switching between material / bootstrap / minimal variants without page reload or flash.',
      priority: 'critical',
      category: 'Theming',
    },
    {
      title: 'Theme Preset Management',
      description:
        'Build a theme preset system with multiple built-in presets (e.g. indigo, ocean, sunset) switchable at runtime.',
      priority: 'critical',
      category: 'Theming',
    },
    {
      title: 'Full Axe-Core Audit',
      description:
        'Run a comprehensive axe-core pass across all 100 components. Target: zero violations.',
      priority: 'high',
      category: 'Accessibility',
    },
    {
      title: 'Storybook Deployment',
      description:
        'Deploy Storybook with stories covering all variants for every component. This is the public-facing demo.',
      priority: 'high',
      category: 'Ecosystem',
    },
    {
      title: 'npm Publication Path',
      description:
        'Prepare package.json, provenance, documentation site, and CI/CD pipeline for first npm publish (0.9.0).',
      priority: 'high',
      category: 'Publishing',
    },
    {
      title: 'Landing Page',
      description:
        'Build "Built Different" landing page with verified a11y benchmark claims, Angular modernity scorecard, and bundle size comparisons.',
      priority: 'medium',
      category: 'Marketing',
    },
    {
      title: 'Push Worst Avg Scores to ≥ 9',
      description:
        'Components scored 8.2–8.3 need a targeted polish pass to close the gap before v1.0 GA (Select, AutoComplete, CascadeSelect, etc.).',
      priority: 'medium',
      category: 'Quality',
    },
    {
      title: 'Documentation Site',
      description:
        'Publish an interactive docs site with live demos, copy-paste examples, API tables, and per-component a11y notes.',
      priority: 'medium',
      category: 'Ecosystem',
    },
  ];

  // ── Wow Factors ───────────────────────────────────────────────────────────
  public readonly wowFactors: WowFactor[] = [
    {
      number: 1,
      title: 'Elite Accessibility',
      tagline:
        'No other Angular library comes close to this level of ARIA correctness and keyboard coverage.',
      status: 'achieved',
      items: [
        '100% of components scored ≥ 8 on accessibility',
        'Full keyboard navigation on all interactive components',
        'Correct ARIA roles, properties, and live regions',
        'prefers-reduced-motion respected everywhere',
        'High-contrast / forced-colors support',
        'Screen-reader tested patterns',
      ],
    },
    {
      number: 2,
      title: 'Astonishingly Good Theming',
      tagline: 'Runtime theme switching, design token system, brand customization in < 30 minutes.',
      status: 'in-progress',
      items: [
        '✅ CSS variable system (--uilib-*) in place across all components',
        '✅ Three variants: material / bootstrap / minimal',
        '✅ ThemeConfigService with scoped theming support',
        '🔄 Runtime variant switcher (no flash)',
        '🔄 Theme preset management (indigo, ocean, sunset…)',
        '⬜ Visual theme builder (horizon)',
        '⬜ Brand customization < 30 min documented path',
      ],
    },
    {
      number: 3,
      title: 'Unmatched Forms Experience',
      tagline: 'Best typed, reactive, signal-native forms DX in Angular — ever.',
      status: 'queued',
      items: [
        'FormField + FloatLabel + InputGroup composition system ✅',
        'Signal-native form control binding',
        'Typed validation with signal-based error state',
        'Complex form patterns (wizard, dynamic fields) first-class',
      ],
    },
    {
      number: 4,
      title: 'Exceptional Developer Experience',
      tagline: 'APIs so predictable developers never reach for docs for basic usage.',
      status: 'queued',
      items: [
        'Zero-config defaults for common use cases',
        'Autocomplete that guides you correctly',
        'Clear error messages for misuse',
        'Consistent naming across all 100 components',
      ],
    },
    {
      number: 5,
      title: 'Unbelievably Polished Animations',
      tagline: 'Motion that makes developers say "how did they do that".',
      status: 'queued',
      items: [
        'Physics-based spring animations',
        'Consistent timing and easing design system',
        'Choreographed enter/exit sequences',
        'All animations controllable via CSS vars',
      ],
    },
    {
      number: 6,
      title: 'The Best Angular Table / Grid',
      tagline: 'Performance + composability that makes every other grid feel old.',
      status: 'queued',
      items: [
        'Virtual scrolling with millions of rows',
        'Column reorder, resize, pin — all accessible',
        'Signal-based state management',
        'Composable cell renderers',
      ],
    },
  ];

  // ── Helpers ───────────────────────────────────────────────────────────────
  public getScoreClass(score: number): string {
    if (score >= 9.5) return 'score-gold';
    if (score >= 9.0) return 'score-excellent';
    if (score >= 8.5) return 'score-good';
    return 'score-ok';
  }

  public getCellClass(score: number): string {
    if (score === 10) return 'cell-perfect';
    if (score === 9) return 'cell-good';
    return 'cell-ok';
  }

  public onSearchChange(event: Event): void {
    const target: HTMLInputElement = event.target as HTMLInputElement;
    this.searchQuery.set(target.value);
  }

  public setCategory(category: string): void {
    this.activeCategory.set(category);
  }

  public trackByName(_index: number, item: ComponentScore): string {
    return item.name;
  }

  public trackByPhaseId(_index: number, phase: PhaseInfo): number {
    return phase.id;
  }

  public trackByTitle(_index: number, step: NextStep): string {
    return step.title;
  }

  public trackByWowNumber(_index: number, wow: WowFactor): number {
    return wow.number;
  }

  public trackByCategory(_index: number, item: { name: string; count: number }): string {
    return item.name;
  }

  public trackByString(_index: number, item: string): string {
    return item;
  }

  public trackByCategoryName(_index: number, item: string): string {
    return item;
  }
}
