import { provideIcons } from '@ng-icons/core';
import { IconMapping } from '../icon.semantics';
import {
  bootstrapX,
  bootstrapList,
  bootstrapSearch,
  bootstrapGear,
  bootstrapPlus,
  bootstrapDash,
  bootstrapPencil,
  bootstrapTrash,
  bootstrapArrowRepeat,
  bootstrapDownload,
  bootstrapUpload,
  bootstrapShare,
  bootstrapHouse,
  bootstrapPerson,
  bootstrapEnvelope,
  bootstrapBell,
  bootstrapStar,
  bootstrapHeart,
  bootstrapInfoCircle,
  bootstrapCheckCircle,
  bootstrapExclamationOctagon,
  bootstrapExclamationTriangle,
  bootstrapArrowRight,
  bootstrapChevronRight,
  bootstrapChevronLeft,
  bootstrapChevronUp,
  bootstrapChevronDown,
} from '@ng-icons/bootstrap-icons';

export const BOOTSTRAP_ICON_MAPPING: IconMapping = {
  close: 'bootstrapX',
  menu: 'bootstrapList',
  search: 'bootstrapSearch',
  settings: 'bootstrapGear',
  add: 'bootstrapPlus',
  remove: 'bootstrapDash',
  edit: 'bootstrapPencil',
  delete: 'bootstrapTrash',
  save: 'bootstrapDownload',
  refresh: 'bootstrapArrowRepeat',
  download: 'bootstrapDownload',
  upload: 'bootstrapUpload',
  share: 'bootstrapShare',
  home: 'bootstrapHouse',
  user: 'bootstrapPerson',
  mail: 'bootstrapEnvelope',
  bell: 'bootstrapBell',
  star: 'bootstrapStar',
  heart: 'bootstrapHeart',
  info: 'bootstrapInfoCircle',
  success: 'bootstrapCheckCircle',
  error: 'bootstrapExclamationOctagon',
  warning: 'bootstrapExclamationTriangle',
  check: 'bootstrapCheckCircle',
  x: 'bootstrapX',
  spinner: 'bootstrapArrowRepeat',
  'chevron-right': 'bootstrapChevronRight',
  'chevron-left': 'bootstrapChevronLeft',
  'chevron-up': 'bootstrapChevronUp',
  'chevron-down': 'bootstrapChevronDown',
  'arrow-right': 'bootstrapArrowRight',
};

export const BOOTSTRAP_ICONS = {
  bootstrapX,
  bootstrapList,
  bootstrapSearch,
  bootstrapGear,
  bootstrapPlus,
  bootstrapDash,
  bootstrapPencil,
  bootstrapTrash,
  bootstrapArrowRepeat,
  bootstrapDownload,
  bootstrapUpload,
  bootstrapShare,
  bootstrapHouse,
  bootstrapPerson,
  bootstrapEnvelope,
  bootstrapBell,
  bootstrapStar,
  bootstrapHeart,
  bootstrapInfoCircle,
  bootstrapCheckCircle,
  bootstrapExclamationOctagon,
  bootstrapExclamationTriangle,
  bootstrapArrowRight,
  bootstrapChevronRight,
  bootstrapChevronLeft,
  bootstrapChevronUp,
  bootstrapChevronDown,
};

export function provideBootstrapIcons(extra: Record<string, unknown> = {}) {
  return provideIcons({ ...BOOTSTRAP_ICONS, ...extra });
}
