import { provideIcons } from '@ng-icons/core';
import {
  lucideAlertCircle,
  lucideAlertTriangle,
  lucideAlignCenter,
  lucideAlignHorizontalJustifyCenter,
  lucideAlignHorizontalSpaceAround,
  lucideAlignHorizontalSpaceBetween,
  lucideAlignJustify,
  lucideAlignLeft,
  lucideAlignRight,
  lucideAlignVerticalDistributeCenter,
  lucideArrowUp,
  lucideArrowUpLeft,
  lucideArrowUpRight,
  lucideArrowUpRightFromSquare,
  lucideArrowUpRightSquare,
  lucideArrowUpSquare,
  lucideArrowUpToLine,
  lucideArrowsUpFromLine,
  lucideAtSign,
  lucideAudioWaveform,
  lucideAward,
  lucideBadge,
  lucideBadgeAlert,
  lucideBadgeCheck,
  lucideBadgeHelp,
  lucideBadgeInfo,
  lucideBadgeMinus,
  lucideBadgePlus,
  lucideBadgeQuestionMark,
  lucideBadgeX,
  lucideBan,
  lucideBarChart,
  lucideBarChart2,
  lucideBarChart3,
  lucideBarChart4,
  lucideBarChartBig,
  lucideBarChartHorizontal,
  lucideBarChartHorizontalBig,
  lucideBarcode,
  lucideBath,
  lucideBattery,
  lucideBatteryCharging,
  lucideBatteryFull,
  lucideBatteryLow,
  lucideBatteryMedium,
  lucideBatteryWarning,
  lucideBeaker,
  lucideBed,
  lucideBellDot,
  lucideBellElectric,
} from '@ng-icons/lucide';
import { IconMapping } from '../icon.semantics';

export const LUCIDE_ICON_MAPPING: IconMapping = {
  // Actions
  close: 'lucideBadgeX',
  menu: 'lucideAlignJustify',
  search: 'lucideAtSign',
  settings: 'lucideBadge',
  more: 'lucideAlignHorizontalSpaceAround',
  add: 'lucideBadgePlus',
  remove: 'lucideBadgeMinus',
  edit: 'lucideBarChart',
  delete: 'lucideBan',
  save: 'lucideAward',
  refresh: 'lucideArrowsUpFromLine',
  sync: 'lucideArrowUpRightFromSquare',
  download: 'lucideArrowUpSquare',
  upload: 'lucideArrowUp',
  share: 'lucideArrowUpRight',
  copy: 'lucideBadgeInfo',
  paste: 'lucideBadgeAlert',
  cut: 'lucideBadgeQuestionMark',
  undo: 'lucideArrowUpLeft',
  redo: 'lucideArrowUpRight',

  // Navigation
  home: 'lucideBadge',
  back: 'lucideArrowUpLeft',
  forward: 'lucideArrowUpRight',
  up: 'lucideArrowUp',
  down: 'lucideArrowUpToLine',
  'chevron-left': 'lucideAlignLeft',
  'chevron-right': 'lucideAlignRight',
  'chevron-up': 'lucideAlignCenter',
  'chevron-down': 'lucideAlignHorizontalJustifyCenter',
  'arrow-left': 'lucideArrowUpLeft',
  'arrow-right': 'lucideArrowUpRight',
  'arrow-up': 'lucideArrowUp',
  'arrow-down': 'lucideArrowUpToLine',
  'external-link': 'lucideArrowUpRightFromSquare',
  link: 'lucideArrowUpRightSquare',

  // Status/feedback
  success: 'lucideBadgeCheck',
  error: 'lucideBadgeX',
  warning: 'lucideAlertTriangle',
  info: 'lucideBadgeInfo',
  check: 'lucideBadgeCheck',
  x: 'lucideBadgeX',
  alert: 'lucideAlertCircle',
  help: 'lucideBadgeHelp',
  loading: 'lucideAudioWaveform',
  spinner: 'lucideAudioWaveform',

  // Objects
  user: 'lucideBadgeInfo',
  users: 'lucideBadgeHelp',
  file: 'lucideBarChart2',
  folder: 'lucideBarChart3',
  image: 'lucideBarChart4',
  document: 'lucideBarChartBig',
  calendar: 'lucideBarChartHorizontal',
  clock: 'lucideBarChartHorizontalBig',
  mail: 'lucideBadgeAlert',
  phone: 'lucideBadgePlus',
  notification: 'lucideBellDot',
  bell: 'lucideBellElectric',
  star: 'lucideAward',
  heart: 'lucideBadge',
  bookmark: 'lucideBadgeInfo',

  // Form
  eye: 'lucideBadgeInfo',
  'eye-off': 'lucideBadgeQuestionMark',
  lock: 'lucideBattery',
  unlock: 'lucideBatteryFull',
  checkbox: 'lucideBadgeCheck',
  radio: 'lucideBadgeInfo',
  dropdown: 'lucideAlignHorizontalSpaceBetween',
};

export const LUCIDE_ICONS = {
  lucideAlertCircle,
  lucideAlertTriangle,
  lucideAlignCenter,
  lucideAlignHorizontalJustifyCenter,
  lucideAlignHorizontalSpaceAround,
  lucideAlignHorizontalSpaceBetween,
  lucideAlignJustify,
  lucideAlignLeft,
  lucideAlignRight,
  lucideAlignVerticalDistributeCenter,
  lucideArrowUp,
  lucideArrowUpLeft,
  lucideArrowUpRight,
  lucideArrowUpRightFromSquare,
  lucideArrowUpRightSquare,
  lucideArrowUpSquare,
  lucideArrowUpToLine,
  lucideArrowsUpFromLine,
  lucideAtSign,
  lucideAudioWaveform,
  lucideAward,
  lucideBadge,
  lucideBadgeAlert,
  lucideBadgeCheck,
  lucideBadgeHelp,
  lucideBadgeInfo,
  lucideBadgeMinus,
  lucideBadgePlus,
  lucideBadgeQuestionMark,
  lucideBadgeX,
  lucideBan,
  lucideBarChart,
  lucideBarChart2,
  lucideBarChart3,
  lucideBarChart4,
  lucideBarChartBig,
  lucideBarChartHorizontal,
  lucideBarChartHorizontalBig,
  lucideBarcode,
  lucideBath,
  lucideBattery,
  lucideBatteryCharging,
  lucideBatteryFull,
  lucideBatteryLow,
  lucideBatteryMedium,
  lucideBatteryWarning,
  lucideBeaker,
  lucideBed,
  lucideBellDot,
  lucideBellElectric,
};

export function provideMinimalIcons(extra: Record<string, unknown> = {}) {
  return provideIcons({ ...LUCIDE_ICONS, ...extra });
}
